In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress

# Import API key


# Incorporated citipy to determine city based on latitude and longitude

from config import gkey
from config import g_key

# Rents 2018-2019

In [2]:
rents_2018 = pd.read_csv("UTF/FY2018_50_County_rev.csv")
rents_2018.head()

,fips2010,rent50_0,rent50_1,rent50_2,rent50_3,rent50_4,state,cbsasub18,areaname18,county,cousub,cntyname,name,pop2010,hu2010,state_alpha
0,100199999,631,742,890,1133,1558,1,METRO33860M33860,"Montgomery, AL MSA",1,99999,Autauga County,Autauga County,54571.0,22135.0,AL
1,100399999,786,809,929,1351,1578,1,METRO19300M19300,"Daphne-Fairhope-Foley, AL MSA",3,99999,Baldwin County,Baldwin County,182265.0,104061.0,AL
2,100599999,527,531,706,885,998,1,NCNTY01005N01005,"Barbour County, AL",5,99999,Barbour County,Barbour County,27457.0,11829.0,AL
3,100799999,749,832,955,1273,1424,1,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",7,99999,Bibb County,Bibb County,22915.0,8981.0,AL
4,100999999,749,832,955,1273,1424,1,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",9,99999,Blount County,Blount County,57322.0,23887.0,AL

In [3]:
rents_2019 = pd.read_csv("UTF/FY2019_50_County_rev.csv")
rents_2019.head()

,fips2010,rent50_0,rent50_1,rent50_2,rent50_3,rent50_4,state,cbsasub19,areaname19,county,cousub,cntyname,name,pop2010,hu2010,state_alpha
0,4805999999,642,667,882,1142,1467,48,METRO10180M10180,"Abilene, TX MSA",59,99999,Callahan County,Callahan County,13544,6549,TX
1,4825399999,642,667,882,1142,1467,48,METRO10180M10180,"Abilene, TX MSA",253,99999,Jones County,Jones County,20202,7422,TX
2,4844199999,642,667,882,1142,1467,48,METRO10180M10180,"Abilene, TX MSA",441,99999,Taylor County,Taylor County,131506,55750,TX
3,7200399999,388,398,456,606,732,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",3,99999,Aguada Municipio,Aguada Municipio,41959,18258,PR
4,7200599999,388,398,456,606,732,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",5,99999,Aguadilla Municipio,Aguadilla Municipio,60949,28430,PR

## Merge tests

In [4]:
rent_18_19 = pd.merge(rents_2018, rents_2019, how="left", on=["state", "county", "cousub"], suffixes=('_2018', '_2019'))
rent_18_19.head()

,fips2010_2018,rent50_0_2018,rent50_1_2018,rent50_2_2018,rent50_3_2018,rent50_4_2018,state,cbsasub18,areaname18,county,...,rent50_2_2019,rent50_3_2019,rent50_4_2019,cbsasub19,areaname19,cntyname_2019,name_2019,pop2010_2019,hu2010_2019,state_alpha_2019
0,100199999,631,742,890,1133,1558,1,METRO33860M33860,"Montgomery, AL MSA",1,...,880.0,1112.0,1532.0,METRO33860M33860,"Montgomery, AL MSA",Autauga County,Autauga County,54571.0,22135.0,AL
1,100399999,786,809,929,1351,1578,1,METRO19300M19300,"Daphne-Fairhope-Foley, AL MSA",3,...,959.0,1352.0,1622.0,METRO19300M19300,"Daphne-Fairhope-Foley, AL MSA",Baldwin County,Baldwin County,182265.0,104061.0,AL
2,100599999,527,531,706,885,998,1,NCNTY01005N01005,"Barbour County, AL",5,...,716.0,901.0,1011.0,NCNTY01005N01005,"Barbour County, AL",Barbour County,Barbour County,27457.0,11829.0,AL
3,100799999,749,832,955,1273,1424,1,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",7,...,943.0,1247.0,1385.0,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",Bibb County,Bibb County,22915.0,8981.0,AL
4,100999999,749,832,955,1273,1424,1,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",9,...,943.0,1247.0,1385.0,METRO13820M13820,"Birmingham-Hoover, AL HUD Metro FMR Area",Blount County,Blount County,57322.0,23887.0,AL

In [5]:
#rent_18_19 = pd.merge(rents_2018, rents_2019, how="left", on=["state", "county", "cousub", "pop2010"], suffixes=('_2018', '_2019'))
#rent_18_19.head().sort_values(["rent50_0_2018"])

## Cleaning Up the Data

In [6]:
rent_18_19.columns

Index(['fips2010_2018', 'rent50_0_2018', 'rent50_1_2018', 'rent50_2_2018',
       'rent50_3_2018', 'rent50_4_2018', 'state', 'cbsasub18', 'areaname18',
       'county', 'cousub', 'cntyname_2018', 'name_2018', 'pop2010_2018',
       'hu2010_2018', 'state_alpha_2018', 'fips2010_2019', 'rent50_0_2019',
       'rent50_1_2019', 'rent50_2_2019', 'rent50_3_2019', 'rent50_4_2019',
       'cbsasub19', 'areaname19', 'cntyname_2019', 'name_2019', 'pop2010_2019',
       'hu2010_2019', 'state_alpha_2019'],
      dtype='object')

In [7]:
cleaned_rent_18_19 = rent_18_19.drop(columns=['fips2010_2018', 'fips2010_2019', 'cbsasub18', 'cbsasub19', 'areaname18', 'areaname19',\
                                              'cntyname_2018', 'name_2018', 'name_2019', 'name_2018', 'state_alpha_2019'])
cleaned_rent_18_19 = cleaned_rent_18_19.rename(columns = {'cntyname_2019': 'county name', 'state_alpha_2018': 'state initials'})

cleaned_rent_18_19 = cleaned_rent_18_19.reindex(columns=["state", "county", "cousub", "county name", "state initials", "rent50_0_2018",\
                                                         "rent50_0_2019", "rent50_1_2018", "rent50_1_2019",\
                                                         "rent50_2_2018", "rent50_2_2019", "rent50_3_2018", "rent50_3_2019",\
                                                         "rent50_4_2018","rent50_4_2019","pop2010_2018", "pop2010_2019",\
                                                         "hu2010_2018", "hu2010_2019"])
cleaned_rent_18_19

,state,county,cousub,county name,state initials,rent50_0_2018,rent50_0_2019,rent50_1_2018,rent50_1_2019,rent50_2_2018,rent50_2_2019,rent50_3_2018,rent50_3_2019,rent50_4_2018,rent50_4_2019,pop2010_2018,pop2010_2019,hu2010_2018,hu2010_2019
0,1,1,99999,Autauga County,AL,631,620.0,742,743.0,890,880.0,1133,1112.0,1558,1532.0,54571.0,54571.0,22135.0,22135.0
1,1,3,99999,Baldwin County,AL,786,816.0,809,835.0,929,959.0,1351,1352.0,1578,1622.0,182265.0,182265.0,104061.0,104061.0
2,1,5,99999,Barbour County,AL,527,538.0,531,541.0,706,716.0,885,901.0,998,1011.0,27457.0,27457.0,11829.0,11829.0
3,1,7,99999,Bibb County,AL,749,763.0,832,824.0,955,943.0,1273,1247.0,1424,1385.0,22915.0,22915.0,8981.0,8981.0
4,1,9,99999,Blount County,AL,749,763.0,832,824.0,955,943.0,1273,1247.0,1424,1385.0,57322.0,57322.0,23887.0,23887.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4767,72,151,99999,Yabucoa Municipio,PR,452,465.0,478,495.0,577,592.0,769,785.0,961,984.0,37941.0,37941.0,15798.0,15798.0
4768,72,153,99999,Yauco Municipio,PR,330,354.0,340,363.0,390,416.0,511,575.0,687,731.0,42043.0,42043.0,18020.0,18020.0
4769,78,10,99999,St. Croix,VI,816,779.0,833,794.0,1017,970.0,1275,1215.0,1385,1311.0,53234.0,53234.0,25275.0,25275.0
4770,78,20,99999,St. John,VI,1084,1034.0,1284,1225.0,1596,1523.0,2001,1908.0,2174,2059.0,4197.0,4197.0,3453.0,3453.0
4771,78,30,99999,St. Thomas,VI,763,744.0,921,897.0,1152,1123.0,1444,1407.0,1569,1518.0,51181.0,51181.0,27173.0,27173.0

# Rent 2020-2022

In [8]:
rents_2020 = pd.read_csv("UTF/FY2020_50_County_rev.csv")
rents_2020.head()

,fips2010,rent50_0,rent50_1,rent50_2,rent50_3,rent50_4,state,cbsasub20,areaname20,county,cousub,cntyname,name,pop2017,hu2017,state_alpha
0,4805999999,673,699,920,1209,1560,48,METRO10180M10180,"Abilene, TX MSA",59,99999,Callahan County,Callahan County,13660,6637,TX
1,4825399999,673,699,920,1209,1560,48,METRO10180M10180,"Abilene, TX MSA",253,99999,Jones County,Jones County,19970,7292,TX
2,4844199999,673,699,920,1209,1560,48,METRO10180M10180,"Abilene, TX MSA",441,99999,Taylor County,Taylor County,135370,56978,TX
3,7200399999,386,397,452,591,713,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",3,99999,Aguada Municipio,Aguada Municipio,39470,17385,PR
4,7200599999,386,397,452,591,713,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",5,99999,Aguadilla Municipio,Aguadilla Municipio,55720,27301,PR

In [9]:
rents_2021 = pd.read_csv("UTF/FY2021_50_County.csv")
rents_2021.head()

,fips2010,rent50_0,rent50_1,rent50_2,rent50_3,rent50_4,state,cbsasub21,areaname21,county,cousub,cntyname,name,pop2017,hu2017,state_alpha
0,4805999999,761,789,1028,1383,1764,48,METRO10180M10180,"Abilene, TX MSA",59,99999,Callahan County,Callahan County,13660,6637,TX
1,4825399999,761,789,1028,1383,1764,48,METRO10180M10180,"Abilene, TX MSA",253,99999,Jones County,Jones County,19970,7292,TX
2,4844199999,761,789,1028,1383,1764,48,METRO10180M10180,"Abilene, TX MSA",441,99999,Taylor County,Taylor County,135370,56978,TX
3,7200399999,401,414,472,602,720,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",3,99999,Aguada Municipio,Aguada Municipio,39470,17385,PR
4,7200599999,401,414,472,602,720,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",5,99999,Aguadilla Municipio,Aguadilla Municipio,55720,27301,PR

In [10]:
rents_2022 = pd.read_csv("UTF/FY2022_FMR_50_county_rev.csv")
rents_2022 = rents_2022.rename(columns = {'state_code': 'state', 'county_code': 'county', 'county_sub_code': 'cousub'})
rents_2022.head()

,state,county,cousub,cntyname,town_name,areaname22,rent_50_0,rent_50_1,rent_50_2,rent_50_3,rent_50_4,cbsasub22,pop2017
0,48,59,99999,Callahan County,NaN,"Abilene, TX MSA",715,760,981,1337,1658,METRO10180M10180,13660
1,48,253,99999,Jones County,NaN,"Abilene, TX MSA",715,760,981,1337,1658,METRO10180M10180,19970
2,48,441,99999,Taylor County,NaN,"Abilene, TX MSA",715,760,981,1337,1658,METRO10180M10180,135370
3,72,3,99999,Aguada Municipio,NaN,"Aguadilla-Isabela, PR MSA",407,423,486,604,711,METRO10380M10380,39470
4,72,5,99999,Aguadilla Municipio,NaN,"Aguadilla-Isabela, PR MSA",407,423,486,604,711,METRO10380M10380,55720

## Merging 2020-2022

In [11]:
rent_20_21 = pd.merge(rents_2020, rents_2021, how="left", on=["state", "county", "cousub"], suffixes=('_2020', '_2021'))
rent_20_21

,fips2010_2020,rent50_0_2020,rent50_1_2020,rent50_2_2020,rent50_3_2020,rent50_4_2020,state,cbsasub20,areaname20,county,...,rent50_2_2021,rent50_3_2021,rent50_4_2021,cbsasub21,areaname21,cntyname_2021,name_2021,pop2017_2021,hu2017_2021,state_alpha_2021
0,4805999999,673,699,920,1209,1560,48,METRO10180M10180,"Abilene, TX MSA",59,...,1028.0,1383.0,1764.0,METRO10180M10180,"Abilene, TX MSA",Callahan County,Callahan County,13660.0,6637.0,TX
1,4825399999,673,699,920,1209,1560,48,METRO10180M10180,"Abilene, TX MSA",253,...,1028.0,1383.0,1764.0,METRO10180M10180,"Abilene, TX MSA",Jones County,Jones County,19970.0,7292.0,TX
2,4844199999,673,699,920,1209,1560,48,METRO10180M10180,"Abilene, TX MSA",441,...,1028.0,1383.0,1764.0,METRO10180M10180,"Abilene, TX MSA",Taylor County,Taylor County,135370.0,56978.0,TX
3,7200399999,386,397,452,591,713,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",3,...,472.0,602.0,720.0,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",Aguada Municipio,Aguada Municipio,39470.0,17385.0,PR
4,7200599999,386,397,452,591,713,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",5,...,472.0,602.0,720.0,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",Aguadilla Municipio,Aguadilla Municipio,55720.0,27301.0,PR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4764,7213399999,370,373,437,582,656,72,NCNTY72923N72923,Puerto Rico HUD Nonmetro Area,133,...,450.0,599.0,666.0,NCNTY72923N72923,Puerto Rico HUD Nonmetro Area,Santa Isabel Municipio,Santa Isabel Municipio,22475.0,9417.0,PR
4765,7214799999,370,373,437,582,656,72,NCNTY72923N72923,Puerto Rico HUD Nonmetro Area,147,...,450.0,599.0,666.0,NCNTY72923N72923,Puerto Rico HUD Nonmetro Area,Vieques Municipio,Vieques Municipio,8930.0,5101.0,PR
4766,7801099999,887,905,1105,1377,1497,78,NCNTY78010N78010,"St. Croix Island, VI",10,...,1154.0,1435.0,1565.0,NCNTY78010N78010,"St. Croix Island, VI",St. Croix,St. Croix,53234.0,25275.0,VI
4767,7802099999,1177,1394,1733,2160,2348,78,NCNTY78020N78020,"St. John Island, VI",20,...,1812.0,2254.0,2457.0,NCNTY78020N78020,"St. John Island, VI",St. John,St. John,4197.0,3453.0,VI
4768,7803099999,829,1000,1251,1559,1695,78,NCNTY78030N78030,"St. Thomas Island, VI",30,...,1307.0,1626.0,1772.0,NCNTY78030N78030,"St. Thomas Island, VI",St. Thomas,St. Thomas,51181.0,27173.0,VI

In [12]:
rent_20_21_22 = pd.merge(rent_20_21, rents_2022, how="left", on=["state", "county", "cousub"])
rent_20_21_22.head()

,fips2010_2020,rent50_0_2020,rent50_1_2020,rent50_2_2020,rent50_3_2020,rent50_4_2020,state,cbsasub20,areaname20,county,...,cntyname,town_name,areaname22,rent_50_0,rent_50_1,rent_50_2,rent_50_3,rent_50_4,cbsasub22,pop2017
0,4805999999,673,699,920,1209,1560,48,METRO10180M10180,"Abilene, TX MSA",59,...,Callahan County,NaN,"Abilene, TX MSA",715.0,760.0,981.0,1337.0,1658.0,METRO10180M10180,13660.0
1,4825399999,673,699,920,1209,1560,48,METRO10180M10180,"Abilene, TX MSA",253,...,Jones County,NaN,"Abilene, TX MSA",715.0,760.0,981.0,1337.0,1658.0,METRO10180M10180,19970.0
2,4844199999,673,699,920,1209,1560,48,METRO10180M10180,"Abilene, TX MSA",441,...,Taylor County,NaN,"Abilene, TX MSA",715.0,760.0,981.0,1337.0,1658.0,METRO10180M10180,135370.0
3,7200399999,386,397,452,591,713,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",3,...,Aguada Municipio,NaN,"Aguadilla-Isabela, PR MSA",407.0,423.0,486.0,604.0,711.0,METRO10380M10380,39470.0
4,7200599999,386,397,452,591,713,72,METRO10380M10380,"Aguadilla-Isabela, PR HUD Metro FMR Area",5,...,Aguadilla Municipio,NaN,"Aguadilla-Isabela, PR MSA",407.0,423.0,486.0,604.0,711.0,METRO10380M10380,55720.0

## Cleaning Data

In [13]:
rent_20_21_22.columns

Index(['fips2010_2020', 'rent50_0_2020', 'rent50_1_2020', 'rent50_2_2020',
       'rent50_3_2020', 'rent50_4_2020', 'state', 'cbsasub20', 'areaname20',
       'county', 'cousub', 'cntyname_2020', 'name_2020', 'pop2017_2020',
       'hu2017_2020', 'state_alpha_2020', 'fips2010_2021', 'rent50_0_2021',
       'rent50_1_2021', 'rent50_2_2021', 'rent50_3_2021', 'rent50_4_2021',
       'cbsasub21', 'areaname21', 'cntyname_2021', 'name_2021', 'pop2017_2021',
       'hu2017_2021', 'state_alpha_2021', 'cntyname', 'town_name',
       'areaname22', 'rent_50_0', 'rent_50_1', 'rent_50_2', 'rent_50_3',
       'rent_50_4', 'cbsasub22', 'pop2017'],
      dtype='object')

In [14]:
cleaned_rent_20_21_22 = rent_20_21_22[['state', 'county', 'cntyname_2020', 'state_alpha_2020',\
                                       'rent50_0_2020', 'rent50_0_2021', 'rent_50_0', 'rent50_1_2020',\
               'rent50_1_2021', 'rent_50_1', 'rent50_2_2020', 'rent50_2_2021', 'rent_50_2', 'rent50_3_2020', 'rent50_3_2021',\
               'rent_50_3', 'rent50_4_2020', 'rent50_4_2021', 'rent_50_4', 'pop2017_2020']]
cleaned_rent_20_21_22 = cleaned_rent_20_21_22.rename(columns = {'state_alpha_2020': 'state initial', 'cntyname_2020': 'county name', 'rent_50_0': 'studio_2022',\
                                                                'rent50_0_2020': 'studio_2020', 'rent50_0_2021': 'studio_2021', 'rent50_1_2020': 'bedroom_1_2020',\
                                                                'rent50_1_2021': 'bedroom_1_2021', 'rent_50_1': 'bedroom_1_2022', 'rent50_2_2020': 'bedroom_2_2020',\
                                                                'rent50_2_2021': 'bedroom_2_2021', 'rent_50_2': 'bedroom_2_2022', 'rent50_3_2020': 'bedroom_3_2020',\
                                                                'rent50_3_2021': 'bedroom_3_2021', 'rent_50_3': 'bedroom_3_2022', 'rent50_4_2020': 'bedroom_4_2020','rent50_4_2021': 'bedroom_4_2021',\
                                                                'rent_50_4': 'bedroom_4_2022', 'pop2017_2020': 'pop2017'})
cleaned_rent_20_21_22 = cleaned_rent_20_21_22.dropna()
cleaned_rent_20_21_22

,state,county,county name,state initial,studio_2020,studio_2021,studio_2022,bedroom_1_2020,bedroom_1_2021,bedroom_1_2022,bedroom_2_2020,bedroom_2_2021,bedroom_2_2022,bedroom_3_2020,bedroom_3_2021,bedroom_3_2022,bedroom_4_2020,bedroom_4_2021,bedroom_4_2022,pop2017
0,48,59,Callahan County,TX,673,761.0,715.0,699,789.0,760.0,920,1028.0,981.0,1209,1383.0,1337.0,1560,1764.0,1658.0,13660
1,48,253,Jones County,TX,673,761.0,715.0,699,789.0,760.0,920,1028.0,981.0,1209,1383.0,1337.0,1560,1764.0,1658.0,19970
2,48,441,Taylor County,TX,673,761.0,715.0,699,789.0,760.0,920,1028.0,981.0,1209,1383.0,1337.0,1560,1764.0,1658.0,135370
3,72,3,Aguada Municipio,PR,386,401.0,407.0,397,414.0,423.0,452,472.0,486.0,591,602.0,604.0,713,720.0,711.0,39470
4,72,5,Aguadilla Municipio,PR,386,401.0,407.0,397,414.0,423.0,452,472.0,486.0,591,602.0,604.0,713,720.0,711.0,55720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4764,72,133,Santa Isabel Municipio,PR,370,386.0,389.0,373,395.0,396.0,437,450.0,451.0,582,599.0,614.0,656,666.0,674.0,22475
4765,72,147,Vieques Municipio,PR,370,386.0,389.0,373,395.0,396.0,437,450.0,451.0,582,599.0,614.0,656,666.0,674.0,8930
4766,78,10,St. Croix,VI,887,926.0,964.0,905,945.0,984.0,1105,1154.0,1201.0,1377,1435.0,1485.0,1497,1565.0,1629.0,53234
4767,78,20,St. John,VI,1177,1230.0,1280.0,1394,1458.0,1517.0,1733,1812.0,1885.0,2160,2254.0,2330.0,2348,2457.0,2556.0,4197
4768,78,30,St. Thomas,VI,829,866.0,904.0,1000,1044.0,1088.0,1251,1307.0,1361.0,1559,1626.0,1682.0,1695,1772.0,1846.0,51181

In [15]:
cleaned_rent_20_21_22.columns

Index(['state', 'county', 'county name', 'state initial', 'studio_2020',
       'studio_2021', 'studio_2022', 'bedroom_1_2020', 'bedroom_1_2021',
       'bedroom_1_2022', 'bedroom_2_2020', 'bedroom_2_2021', 'bedroom_2_2022',
       'bedroom_3_2020', 'bedroom_3_2021', 'bedroom_3_2022', 'bedroom_4_2020',
       'bedroom_4_2021', 'bedroom_4_2022', 'pop2017'],
      dtype='object')

In [16]:
cleaned_rent_20_21_22.to_csv("rent20-22.csv")

In [17]:
cleaned_rent_20_21_22[cleaned_rent_20_21_22.isna().any(axis=1)]

Empty DataFrame
Columns: [state, county, county name, state initial, studio_2020, studio_2021, studio_2022, bedroom_1_2020, bedroom_1_2021, bedroom_1_2022, bedroom_2_2020, bedroom_2_2021, bedroom_2_2022, bedroom_3_2020, bedroom_3_2021, bedroom_3_2022, bedroom_4_2020, bedroom_4_2021, bedroom_4_2022, pop2017]
Index: []

In [18]:
GeorgiaStudy = cleaned_rent_20_21_22.loc[cleaned_rent_20_21_22['state initial'] == 'GA']
GeorgiaStudyCounty = GeorgiaStudy.rename(columns = {'county name':'County'})
GeorgiaStudyCounty

,state,county,County,state initial,studio_2020,studio_2021,studio_2022,bedroom_1_2020,bedroom_1_2021,bedroom_1_2022,bedroom_2_2020,bedroom_2_2021,bedroom_2_2022,bedroom_3_2020,bedroom_3_2021,bedroom_3_2022,bedroom_4_2020,bedroom_4_2021,bedroom_4_2022,pop2017
14,13,7,Baker County,GA,643,668.0,562.0,666,690.0,581.0,791,814.0,704.0,1031,1054.0,887.0,1151,1215.0,1036.0,3250
15,13,95,Dougherty County,GA,643,668.0,711.0,666,690.0,737.0,791,814.0,865.0,1031,1054.0,1121.0,1151,1215.0,1359.0,91520
16,13,177,Lee County,GA,643,668.0,711.0,666,690.0,737.0,791,814.0,865.0,1031,1054.0,1121.0,1151,1215.0,1359.0,29215
17,13,273,Terrell County,GA,643,668.0,711.0,666,690.0,737.0,791,814.0,865.0,1031,1054.0,1121.0,1151,1215.0,1359.0,8980
18,13,321,Worth County,GA,643,668.0,711.0,666,690.0,737.0,791,814.0,865.0,1031,1054.0,1121.0,1151,1215.0,1359.0,20810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2295,13,309,Wheeler County,GA,513,507.0,545.0,516,510.0,549.0,651,648.0,704.0,939,927.0,870.0,998,975.0,955.0,7950
2296,13,311,White County,GA,602,619.0,693.0,606,623.0,698.0,764,763.0,827.0,1010,1006.0,1052.0,1035,1035.0,1121.0,28510
2297,13,315,Wilcox County,GA,513,507.0,545.0,516,510.0,549.0,651,648.0,704.0,811,865.0,1000.0,998,975.0,1036.0,8895
2298,13,317,Wilkes County,GA,557,558.0,592.0,560,562.0,596.0,738,740.0,784.0,939,975.0,1035.0,1132,1114.0,1154.0,9905
2299,13,319,Wilkinson County,GA,538,527.0,607.0,542,530.0,611.0,683,699.0,731.0,851,869.0,904.0,1097,979.0,991.0,9145

In [73]:
countySeats = pd.read_csv("list-counties-georgia.csv")
countySeats.head()

   Sr.No           County  FIPS code    County seat  Established
0      1   Appling County          1         Baxley         1818
1      2  Atkinson County          3        Pearson         1917
2      3     Bacon County          5           Alma         1914
3      4     Baker County          7         Newton         1825
4      5   Baldwin County          9  Milledgeville         1803

In [74]:
countySeatsMerge = pd.merge(GeorgiaStudyCounty, countySeats, how="left", on=["County"])
countySeatsMerge.head()

,state,county,County,state initial,studio_2020,studio_2021,studio_2022,bedroom_1_2020,bedroom_1_2021,bedroom_1_2022,...,bedroom_3_2021,bedroom_3_2022,bedroom_4_2020,bedroom_4_2021,bedroom_4_2022,pop2017,Sr.No,FIPS code,County seat,Established
0,13,7,Baker County,GA,643,668.0,562.0,666,690.0,581.0,...,1054.0,887.0,1151,1215.0,1036.0,3250,4,7,Newton,1825
1,13,95,Dougherty County,GA,643,668.0,711.0,666,690.0,737.0,...,1054.0,1121.0,1151,1215.0,1359.0,91520,47,95,Albany,1853
2,13,177,Lee County,GA,643,668.0,711.0,666,690.0,737.0,...,1054.0,1121.0,1151,1215.0,1359.0,29215,88,177,Leesburg,1826
3,13,273,Terrell County,GA,643,668.0,711.0,666,690.0,737.0,...,1054.0,1121.0,1151,1215.0,1359.0,8980,135,273,Dawson,1856
4,13,321,Worth County,GA,643,668.0,711.0,666,690.0,737.0,...,1054.0,1121.0,1151,1215.0,1359.0,20810,159,321,Sylvester,1853

In [75]:
cleningDataGeorgia = countySeatsMerge[['County','state initial','bedroom_1_2021','pop2017','County seat']]
cleningDataGeorgia.head()

             County state initial  bedroom_1_2021  pop2017 County seat
0      Baker County            GA           690.0     3250      Newton
1  Dougherty County            GA           690.0    91520      Albany
2        Lee County            GA           690.0    29215    Leesburg
3    Terrell County            GA           690.0     8980      Dawson
4      Worth County            GA           690.0    20810   Sylvester

In [70]:
base_url = "https://maps.googleapis.com/maps/api/geocode/json"
Lat=[]
Lng=[]
countySeatsGa= []
countySeatstest = cleningDataGeorgia['County seat'].tolist()
for x in countySeatstest:
    target_city = f"{x}, Georgia"
    params = {"address": target_city, "key": g_key}
    
    response = requests.get(base_url, params=params).json()
    
    try:
        lat = response["results"][0]["geometry"]["location"]["lat"]
        lng = response["results"][0]["geometry"]["location"]["lng"]
        Lat.append(lat)
        Lng.append(lng)
        countySeatsGa.append(target_city)
        print(f"{target_city} found!")
    except:
        print(f"{target_city} not found, skipping")
# Extract lat/lng
    
# Print results
print("done")

Newton, Georgia found!
Albany, Georgia found!
Leesburg, Georgia found!
Dawson, Georgia found!
Sylvester, Georgia found!
Athens, Georgia found!
Danielsville, Georgia found!
Watkinsville, Georgia found!
Lexington, Georgia found!
Winder, Georgia found!
Cartersville, Georgia found!
Carrollton, Georgia found!
Canton, Georgia found!
Jonesboro, Georgia found!
Marietta, Georgia found!
Newnan, Georgia found!
Dawsonville, Georgia found!
Decatur, Georgia found!
Douglasville, Georgia found!
Fayetteville, Georgia found!
Cumming, Georgia found!
Atlanta, Georgia found!
Lawrenceville, Georgia found!
Franklin, Georgia found!
McDonough, Georgia found!
Monticello, Georgia found!
Covington, Georgia found!
Dallas, Georgia found!
Jasper, Georgia found!
Zebulon, Georgia found!
Conyers, Georgia found!
Griffin, Georgia found!
Monroe, Georgia found!
Jackson, Georgia found!
Buchanan, Georgia found!
Barnesville, Georgia found!
Greenville, Georgia found!
Madison, Georgia found!
Waynesboro, Georgia found!
Appling, Georgia found!
Thomson, Georgia found!
Augusta, Georgia found!
Lincolnton, Georgia found!
Nahunta, Georgia found!
Brunswick, Georgia found!
Darien, Georgia found!
Ringgold, Georgia found!
Trenton, Georgia found!
Lafayette, Georgia found!
Cusseta, Georgia found!
Hamilton, Georgia found!
Buena Vista, Georgia found!
Columbus, Georgia found!
Dalton, Georgia found!
Chatsworth, Georgia found!
Gainesville, Georgia found!
Hinesville, Georgia found!
Ludowici, Georgia found!
Macon, Georgia found!
Knoxville, Georgia found!
Gray, Georgia found!
Jeffersonville, Georgia found!
Forsyth, Georgia found!
Rome, Georgia found!
Pembroke, Georgia found!
Savannah, Georgia found!
Springfield, Georgia found!
Quitman, Georgia found!
Statenville, Georgia found!
Lakeland, Georgia found!
Valdosta, Georgia found!
Perry, Georgia found!
Fort Valley, Georgia found!
Hawkinsville, Georgia found!
Baxley, Georgia found!
Pearson, Georgia found!
Alma, Georgia found!
Milledgeville, Georgia found!
Homer, Georgia found!
Fitzgerald, Georgia found!
Nashville, Georgia found!
Cochran, Georgia found!
Statesboro, Georgia found!
Morgan, Georgia found!
Woodbine, Georgia found!
Metter, Georgia found!
Folkston, Georgia found!
Summerville, Georgia found!
Fort Gaines, Georgia found!
Homerville, Georgia found!
Douglas, Georgia found!
Moultrie, Georgia found!
Adel, Georgia found!
Cordele, Georgia found!
Bainbridge, Georgia found!
Eastman, Georgia found!
Vienna, Georgia found!
Blakely, Georgia found!
Elberton, Georgia found!
Swainsboro, Georgia found!
Claxton, Georgia found!
Blue Ridge, Georgia found!
Carnesville, Georgia found!
Ellijay, Georgia found!
Gibson, Georgia found!
Calhoun, Georgia found!
Cairo, Georgia found!
Greensboro, Georgia found!
Clarkesville, Georgia found!
Sparta, Georgia found!
Hartwell, Georgia found!
Ocilla, Georgia found!
Jefferson, Georgia found!
Hazlehurst, Georgia found!
Louisville, Georgia found!
Millen, Georgia found!
Wrightsville, Georgia found!
Dublin, Georgia found!
Dahlonega, Georgia found!
Oglethorpe, Georgia found!
Colquitt, Georgia found!
Camilla, Georgia found!
Mount Vernon, Georgia found!
Blackshear, Georgia found!
Cedartown, Georgia found!
Eatonton, Georgia found!
Georgetown, Georgia found!
Clayton, Georgia found!
Cuthbert, Georgia found!
Ellaville, Georgia found!
Sylvania, Georgia found!
Donalsonville, Georgia found!
Toccoa, Georgia found!
Lumpkin, Georgia found!
Americus, Georgia found!
Talbotton, Georgia found!
Crawfordville, Georgia found!
Reidsville, Georgia found!
Butler, Georgia found!
McRae, Georgia found!
Thomasville, Georgia found!
Tifton, Georgia found!
Lyons, Georgia found!
Hiawassee, Georgia found!
Soperton, Georgia found!
Lagrange, Georgia found!
Ashburn, Georgia found!
Blairsville, Georgia found!
Thomaston, Georgia found!
Waycross, Georgia found!
Warrenton, Georgia found!
Sandersville, Georgia found!
Jesup, Georgia found!
Preston, Georgia found!
Alamo, Georgia found!
Cleveland, Georgia found!
Abbeville, Georgia found!
Washington, Georgia found!
Irwinton, Georgia found!
done

In [72]:
cleningDataGeorgia['Lat']= Lat
cleningDataGeorgia['Lng']= Lng
cleningDataGeorgia

/var/folders/2w/fy2bjdfs7nz5_675nfk08_jh0000gp/T/ipykernel_67383/81516993.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleningDataGeorgia['Lat']= Lat
/var/folders/2w/fy2bjdfs7nz5_675nfk08_jh0000gp/T/ipykernel_67383/81516993.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleningDataGeorgia['Lng']= Lng

,County,state initial,bedroom_1_2021,pop2017,County seat,Lat,Lng
0,Baker County,GA,690.0,3250,Newton,31.312957,-84.335742
1,Dougherty County,GA,690.0,91520,Albany,31.578507,-84.155741
2,Lee County,GA,690.0,29215,Leesburg,31.732116,-84.170742
3,Terrell County,GA,690.0,8980,Dawson,31.773500,-84.446583
4,Worth County,GA,690.0,20810,Sylvester,31.530735,-83.835454
...,...,...,...,...,...,...,...
154,Wheeler County,GA,510.0,7950,Alamo,32.147120,-82.777917
155,White County,GA,623.0,28510,Cleveland,34.597040,-83.763237
156,Wilcox County,GA,510.0,8895,Abbeville,31.992122,-83.306824
157,Wilkes County,GA,562.0,9905,Washington,33.736795,-82.739309
158,Wilkinson County,GA,530.0,9145,Irwinton,32.811259,-83.172654